# -*- coding: utf-8 -*-
"""data science logistic reg

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sX3AomGPyJTaweItY7qlWvkilxVKrwdD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_excel("/Craigslist Car Dataset.xlsx")

df.head()

X = df[['year make model','odometer','condition']]
print(X)
df.dropna(inplace=True)

Y = df['price']
print(Y)

from sklearn import preprocessing
le=preprocessing.LabelEncoder()
df['condition']=le.fit_transform(df['condition'])
df['year ,make, model']=le.fit_transform(df['year make model'])
print(df.head)

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(df[['year make model','odometer','condition']],df['price'],test_size=0.2,random_state=0)
print(X_train)
print(X_test)
print(Y_train)
print(Y_test)

from sklearn.linear_model import LogisticRegression as logisticregression
logres= logisticregression()
logres.fit(X_train,Y_train)
Y_pred=logres.predict(X_test)
print(Y_pred)