# -*- coding: utf-8 -*-
"""linear _regression _single_ sklearn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N1WytCdpx-E11rW7pZwrLuqZINBC9KdU
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics r2_score

#read data
df=pd.read_csv("/content/archive (3).zip")
df

#df.tail

x=df["Heads ize(cm^3)"].values
y=df["Brain weight(grams)"].values
#print(x)
#print(y)

# model initiallization
reg = LinearRegression()
#model fitting
reg =reg.fit(x,y)
#y_pred = reg.predict
y_pred = reg.predicticted(y)